net: core: sysctl_net_core.c: declare "one" variable
* It was introduced here: https://github.com/skinzor/nova_stock_kernel/commit/c442d9ede369f639a22244034a55ccbb32d58ccf#diff-5e453bd562a253931e1aab229d9fa2eeR372
* https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable.git/+/v3.18.50/net/core/sysctl_net_core.c#26

* Fix the following build error:

  CC      net/core/flow_dissector.o
  CC      net/core/sysctl_net_core.o
../../../../../../kernel/huawei/msm8953/net/core/sysctl_net_core.c:372:15: error: 'one' undeclared here (not in a function)
   .extra1  = &one,
               ^
make[4]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/scripts/Makefile.build:258: net/core/sysctl_net_core.o] Error 1
make[3]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/scripts/Makefile.build:402: net/core] Error 2
make[2]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/Makefile:959: net] Error 2
make[2]: Leaving directory '/home/robert/Nova/LOS14/out/target/product/hwcan/obj/KERNEL_OBJ'
make[1]: *** [Makefile:145: sub-make] Error 2
make[1]: Leaving directory '/home/robert/Nova/LOS14/kernel/huawei/msm8953'
make: *** [vendor/cm/build/tasks/kernel.mk:282: TARGET_KERNEL_BINARIES] Error 2